package com.teamfractal.xkdeco.common.block.init;

import com.teamfractal.xkdeco.common.block.*;
import com.teamfractal.xkdeco.common.block.roofrelevant.*;
import com.teamfractal.xkdeco.common.util.XKRegistryHandler;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.fmllegacy.RegistryObject;

public class XKRoofRelevantBlocks {

    public static RegistryObject<Block> blackEaveBlock;
    public static RegistryObject<Block> blackEaveSideBlock;
    public static RegistryObject<Block> blackRidgeDecoBlock;
    public static RegistryObject<Block> blackRidgeDecoCenterBlock;
    public static RegistryObject<Block> blackRidgeDecoObliqueBlock;
    public static RegistryObject<Block> blackRoofBlock;
    public static RegistryObject<Block> blackRoofFlatBlock;
    public static RegistryObject<Block> blackRoofGentleBlock;
    public static RegistryObject<Block> blackRoofGentleSideBlock;
    public static RegistryObject<Block> blackRoofRidgeBlock;
    public static RegistryObject<Block> blackRoofSideBlock;
    public static RegistryObject<Block> blackRoofSteepBlock;
    public static RegistryObject<Block> blackRoofSteepSideBlock;
    public static RegistryObject<Block> blackTilesBlock;
    public static RegistryObject<Block> blackTileSlabBlock;
    public static RegistryObject<Block> blackTileStairBlock;
    public static RegistryObject<Block> smallBlackEaveBlock;
    public static RegistryObject<Block> smallBlackEaveSideBlock;
    public static RegistryObject<Block> smallBlackRoofGentleSideBlock;
    public static RegistryObject<Block> smallBlackRoofSideBlock;
    public static RegistryObject<Block> smallBlackRoofSteepSideBlock;

    public static RegistryObject<Block> cyanEaveBlock;
    public static RegistryObject<Block> cyanEaveSideBlock;
    public static RegistryObject<Block> cyanRidgeDecoBlock;
    public static RegistryObject<Block> cyanRidgeDecoCenterBlock;
    public static RegistryObject<Block> cyanRidgeDecoObliqueBlock;
    public static RegistryObject<Block> cyanRoofBlock;
    public static RegistryObject<Block> cyanRoofFlatBlock;
    public static RegistryObject<Block> cyanRoofGentleBlock;
    public static RegistryObject<Block> cyanRoofGentleSideBlock;
    public static RegistryObject<Block> cyanRoofRidgeBlock;
    public static RegistryObject<Block> cyanRoofSideBlock;
    public static RegistryObject<Block> cyanRoofSteepBlock;
    public static RegistryObject<Block> cyanRoofSteepSideBlock;
    public static RegistryObject<Block> cyanTilesBlock;
    public static RegistryObject<Block> cyanTileSlabBlock;
    public static RegistryObject<Block> cyanTileStairBlock;
    public static RegistryObject<Block> smallCyanEaveBlock;
    public static RegistryObject<Block> smallCyanEaveSideBlock;
    public static RegistryObject<Block> smallCyanRoofGentleSideBlock;
    public static RegistryObject<Block> smallCyanRoofSideBlock;
    public static RegistryObject<Block> smallCyanRoofSteepSideBlock;

    public static RegistryObject<Block> yellowEaveBlock;
    public static RegistryObject<Block> yellowEaveSideBlock;
    public static RegistryObject<Block> yellowRidgeDecoBlock;
    public static RegistryObject<Block> yellowRidgeDecoCenterBlock;
    public static RegistryObject<Block> yellowRidgeDecoObliqueBlock;
    public static RegistryObject<Block> yellowRoofBlock;
    public static RegistryObject<Block> yellowRoofFlatBlock;
    public static RegistryObject<Block> yellowRoofGentleBlock;
    public static RegistryObject<Block> yellowRoofGentleSideBlock;
    public static RegistryObject<Block> yellowRoofRidgeBlock;
    public static RegistryObject<Block> yellowRoofSideBlock;
    public static RegistryObject<Block> yellowRoofSteepBlock;
    public static RegistryObject<Block> yellowRoofSteepSideBlock;
    public static RegistryObject<Block> yellowTilesBlock;
    public static RegistryObject<Block> yellowTileSlabBlock;
    public static RegistryObject<Block> yellowTileStairBlock;
    public static RegistryObject<Block> smallYellowEaveBlock;
    public static RegistryObject<Block> smallYellowEaveSideBlock;
    public static RegistryObject<Block> smallYellowRoofGentleSideBlock;
    public static RegistryObject<Block> smallYellowRoofSideBlock;
    public static RegistryObject<Block> smallYellowRoofSteepSideBlock;

    public static RegistryObject<Block> greenEaveBlock;
    public static RegistryObject<Block> greenEaveSideBlock;
    public static RegistryObject<Block> greenRoofBlock;
    public static RegistryObject<Block> greenRoofGentleBlock;
    public static RegistryObject<Block> greenRoofGentleSideBlock;
    public static RegistryObject<Block> greenRoofRidgeBlock;
    public static RegistryObject<Block> greenRoofSideBlock;
    public static RegistryObject<Block> greenRoofSteepBlock;
    public static RegistryObject<Block> greenRoofSteepSideBlock;
    public static RegistryObject<Block> greenTilesBlock;
    public static RegistryObject<Block> greenTileSlabBlock;
    public static RegistryObject<Block> greenTileStairBlock;

    public static RegistryObject<Block> redEaveBlock;
    public static RegistryObject<Block> redEaveSideBlock;
    public static RegistryObject<Block> redRoofBlock;
    public static RegistryObject<Block> redRoofGentleBlock;
    public static RegistryObject<Block> redRoofGentleSideBlock;
    public static RegistryObject<Block> redRoofRidgeBlock;
    public static RegistryObject<Block> redRoofSideBlock;
    public static RegistryObject<Block> redRoofSteepBlock;
    public static RegistryObject<Block> redRoofSteepSideBlock;
    public static RegistryObject<Block> redTilesBlock;
    public static RegistryObject<Block> redTileSlabBlock;
    public static RegistryObject<Block> redTileStairBlock;

    public static RegistryObject<Block> blueEaveBlock;
    public static RegistryObject<Block> blueEaveSideBlock;
    public static RegistryObject<Block> blueRoofBlock;
    public static RegistryObject<Block> blueRoofGentleBlock;
    public static RegistryObject<Block> blueRoofGentleSideBlock;
    public static RegistryObject<Block> blueRoofRidgeBlock;
    public static RegistryObject<Block> blueRoofSideBlock;
    public static RegistryObject<Block> blueRoofSteepBlock;
    public static RegistryObject<Block> blueRoofSteepSideBlock;
    public static RegistryObject<Block> blueTilesBlock;
    public static RegistryObject<Block> blueTileSlabBlock;
    public static RegistryObject<Block> blueTileStairBlock;

    public static void register(){
        blackEaveBlock = XKRegistryHandler.Blocks.register("black_roof_eave", GenericStairBlock::new);
        blackEaveSideBlock = XKRegistryHandler.Blocks.register("black_roof_eave_side", GenericStairBlock::new);
        blackRidgeDecoBlock = XKRegistryHandler.Blocks.register("black_ridge_deco", GenericStairBlock::new);
        blackRidgeDecoCenterBlock = XKRegistryHandler.Blocks.register("black_ridge_deco_center", GenericSlabBlock::new);
        blackRidgeDecoObliqueBlock = XKRegistryHandler.Blocks.register("black_ridge_deco_oblique", GenericStairBlock::new);
        blackRoofBlock = XKRegistryHandler.Blocks.register("black_roof", GenericStairBlock::new);
        blackRoofFlatBlock = XKRegistryHandler.Blocks.register("black_roof_flat", RoofFlatBlock::new);
        blackRoofGentleBlock = XKRegistryHandler.Blocks.register("black_roof_gentle", GenericStairBlock::new);
        blackRoofGentleSideBlock = XKRegistryHandler.Blocks.register("black_roof_gentle_side", GenericStairBlock::new);
        blackRoofRidgeBlock = XKRegistryHandler.Blocks.register("black_roof_ridge", RoofRidgeBlock::new);
        blackRoofSideBlock = XKRegistryHandler.Blocks.register("black_roof_side", GenericStairBlock::new);
        blackRoofSteepBlock = XKRegistryHandler.Blocks.register("black_roof_steep", GenericStairBlock::new);
        blackRoofSteepSideBlock = XKRegistryHandler.Blocks.register("black_roof_steep_side", GenericStairBlock::new);
        blackTilesBlock = XKRegistryHandler.Blocks.register("black_tiles", TilesBlock::new);
        blackTileSlabBlock = XKRegistryHandler.Blocks.register("black_tile_slab", GenericSlabBlock::new);
        blackTileStairBlock = XKRegistryHandler.Blocks.register("black_tile_stair", TileStairBlock::new);
        smallBlackEaveBlock = XKRegistryHandler.Blocks.register("small_black_roof_eave", GenericStairBlock::new);
        smallBlackEaveSideBlock = XKRegistryHandler.Blocks.register("small_black_roof_eave_side", GenericStairBlock::new);
        smallBlackRoofGentleSideBlock = XKRegistryHandler.Blocks.register("small_black_roof_gentle_side", GenericStairBlock::new);
        smallBlackRoofSideBlock = XKRegistryHandler.Blocks.register("small_black_roof_side", GenericStairBlock::new);
        smallBlackRoofSteepSideBlock = XKRegistryHandler.Blocks.register("small_black_roof_steep_side", GenericStairBlock::new);


        cyanEaveBlock = XKRegistryHandler.Blocks.register("cyan_roof_eave", GenericStairBlock::new);
        cyanEaveSideBlock = XKRegistryHandler.Blocks.register("cyan_roof_eave_side", GenericStairBlock::new);
        cyanRidgeDecoBlock = XKRegistryHandler.Blocks.register("cyan_ridge_deco", GenericStairBlock::new);
        cyanRidgeDecoCenterBlock = XKRegistryHandler.Blocks.register("cyan_ridge_deco_center", GenericSlabBlock::new);
        cyanRidgeDecoObliqueBlock = XKRegistryHandler.Blocks.register("cyan_ridge_deco_oblique", GenericStairBlock::new);
        cyanRoofBlock = XKRegistryHandler.Blocks.register("cyan_roof", GenericStairBlock::new);
        cyanRoofFlatBlock = XKRegistryHandler.Blocks.register("cyan_roof_flat", RoofFlatBlock::new);
        cyanRoofGentleBlock = XKRegistryHandler.Blocks.register("cyan_roof_gentle", GenericStairBlock::new);
        cyanRoofGentleSideBlock = XKRegistryHandler.Blocks.register("cyan_roof_gentle_side", GenericStairBlock::new);
        cyanRoofRidgeBlock = XKRegistryHandler.Blocks.register("cyan_roof_ridge", RoofRidgeBlock::new);
        cyanRoofSideBlock = XKRegistryHandler.Blocks.register("cyan_roof_side", GenericStairBlock::new);
        cyanRoofSteepBlock = XKRegistryHandler.Blocks.register("cyan_roof_steep", GenericStairBlock::new);
        cyanRoofSteepSideBlock = XKRegistryHandler.Blocks.register("cyan_roof_steep_side", GenericStairBlock::new);
        cyanTilesBlock = XKRegistryHandler.Blocks.register("cyan_tiles", TilesBlock::new);
        cyanTileSlabBlock = XKRegistryHandler.Blocks.register("cyan_tile_slab", GenericSlabBlock::new);
        cyanTileStairBlock = XKRegistryHandler.Blocks.register("cyan_tile_stair", TileStairBlock::new);
        smallCyanEaveBlock = XKRegistryHandler.Blocks.register("small_cyan_roof_eave", GenericStairBlock::new);
        smallCyanEaveSideBlock = XKRegistryHandler.Blocks.register("small_cyan_roof_eave_side", GenericStairBlock::new);
        smallCyanRoofGentleSideBlock = XKRegistryHandler.Blocks.register("small_cyan_roof_gentle_side", GenericStairBlock::new);
        smallCyanRoofSideBlock = XKRegistryHandler.Blocks.register("small_cyan_roof_side", GenericStairBlock::new);
        smallCyanRoofSteepSideBlock = XKRegistryHandler.Blocks.register("small_cyan_roof_steep_side", GenericStairBlock::new);

        yellowEaveBlock = XKRegistryHandler.Blocks.register("yellow_roof_eave", GenericStairBlock::new);
        yellowEaveSideBlock = XKRegistryHandler.Blocks.register("yellow_roof_eave_side", GenericStairBlock::new);
        yellowRidgeDecoBlock = XKRegistryHandler.Blocks.register("yellow_ridge_deco", GenericStairBlock::new);
        yellowRidgeDecoCenterBlock = XKRegistryHandler.Blocks.register("yellow_ridge_deco_center", GenericSlabBlock::new);
        yellowRidgeDecoObliqueBlock = XKRegistryHandler.Blocks.register("yellow_ridge_deco_oblique", GenericStairBlock::new);
        yellowRoofBlock = XKRegistryHandler.Blocks.register("yellow_roof", GenericStairBlock::new);
        yellowRoofFlatBlock = XKRegistryHandler.Blocks.register("yellow_roof_flat", RoofFlatBlock::new);
        yellowRoofGentleBlock = XKRegistryHandler.Blocks.register("yellow_roof_gentle", GenericStairBlock::new);
        yellowRoofGentleSideBlock = XKRegistryHandler.Blocks.register("yellow_roof_gentle_side", GenericStairBlock::new);
        yellowRoofRidgeBlock = XKRegistryHandler.Blocks.register("yellow_roof_ridge", RoofRidgeBlock::new);
        yellowRoofSideBlock = XKRegistryHandler.Blocks.register("yellow_roof_side", GenericStairBlock::new);
        yellowRoofSteepBlock = XKRegistryHandler.Blocks.register("yellow_roof_steep", GenericStairBlock::new);
        yellowRoofSteepSideBlock = XKRegistryHandler.Blocks.register("yellow_roof_steep_side", GenericStairBlock::new);
        yellowTilesBlock = XKRegistryHandler.Blocks.register("yellow_tiles", TilesBlock::new);
        yellowTileSlabBlock = XKRegistryHandler.Blocks.register("yellow_tile_slab", GenericSlabBlock::new);
        yellowTileStairBlock = XKRegistryHandler.Blocks.register("yellow_tile_stair", TileStairBlock::new);
        smallYellowEaveBlock = XKRegistryHandler.Blocks.register("small_yellow_roof_eave", GenericStairBlock::new);
        smallYellowEaveSideBlock = XKRegistryHandler.Blocks.register("small_yellow_roof_eave_side", GenericStairBlock::new);
        smallYellowRoofGentleSideBlock = XKRegistryHandler.Blocks.register("small_yellow_roof_gentle_side", GenericStairBlock::new);
        smallYellowRoofSideBlock = XKRegistryHandler.Blocks.register("small_yellow_roof_side", GenericStairBlock::new);
        smallYellowRoofSteepSideBlock = XKRegistryHandler.Blocks.register("small_yellow_roof_steep_side", GenericStairBlock::new);

        greenEaveBlock = XKRegistryHandler.Blocks.register("green_roof_eave", GenericStairBlock::new);
        greenEaveSideBlock = XKRegistryHandler.Blocks.register("green_roof_eave_side", GenericStairBlock::new);
        greenRoofBlock = XKRegistryHandler.Blocks.register("green_roof", GenericStairBlock::new);
        greenRoofGentleBlock = XKRegistryHandler.Blocks.register("green_roof_gentle", GenericStairBlock::new);
        greenRoofGentleSideBlock = XKRegistryHandler.Blocks.register("green_roof_gentle_side", GenericStairBlock::new);
        greenRoofRidgeBlock = XKRegistryHandler.Blocks.register("green_roof_ridge", RoofRidgeBlock::new);
        greenRoofSideBlock = XKRegistryHandler.Blocks.register("green_roof_side", GenericStairBlock::new);
        greenRoofSteepBlock = XKRegistryHandler.Blocks.register("green_roof_steep", GenericStairBlock::new);
        greenRoofSteepSideBlock = XKRegistryHandler.Blocks.register("green_roof_steep_side", GenericStairBlock::new);
        greenTilesBlock = XKRegistryHandler.Blocks.register("green_tiles", TilesBlock::new);
        greenTileSlabBlock = XKRegistryHandler.Blocks.register("green_tile_slab", GenericSlabBlock::new);
        greenTileStairBlock = XKRegistryHandler.Blocks.register("green_tile_stair", TileStairBlock::new);

        redEaveBlock = XKRegistryHandler.Blocks.register("red_roof_eave", GenericStairBlock::new);
        redEaveSideBlock = XKRegistryHandler.Blocks.register("red_roof_eave_side", GenericStairBlock::new);
        redRoofBlock = XKRegistryHandler.Blocks.register("red_roof", GenericStairBlock::new);
        redRoofGentleBlock = XKRegistryHandler.Blocks.register("red_roof_gentle", GenericStairBlock::new);
        redRoofGentleSideBlock = XKRegistryHandler.Blocks.register("red_roof_gentle_side", GenericStairBlock::new);
        redRoofRidgeBlock = XKRegistryHandler.Blocks.register("red_roof_ridge", RoofRidgeBlock::new);
        redRoofSideBlock = XKRegistryHandler.Blocks.register("red_roof_side", GenericStairBlock::new);
        redRoofSteepBlock = XKRegistryHandler.Blocks.register("red_roof_steep", GenericStairBlock::new);
        redRoofSteepSideBlock = XKRegistryHandler.Blocks.register("red_roof_steep_side", GenericStairBlock::new);
        redTilesBlock = XKRegistryHandler.Blocks.register("red_tiles", TilesBlock::new);
        redTileSlabBlock = XKRegistryHandler.Blocks.register("red_tile_slab", GenericSlabBlock::new);
        redTileStairBlock = XKRegistryHandler.Blocks.register("red_tile_stair", TileStairBlock::new);

        blueEaveBlock = XKRegistryHandler.Blocks.register("blue_roof_eave", GenericStairBlock::new);
        blueEaveSideBlock = XKRegistryHandler.Blocks.register("blue_roof_eave_side", GenericStairBlock::new);
        blueRoofBlock = XKRegistryHandler.Blocks.register("blue_roof", GenericStairBlock::new);
        blueRoofGentleBlock = XKRegistryHandler.Blocks.register("blue_roof_gentle", GenericStairBlock::new);
        blueRoofGentleSideBlock = XKRegistryHandler.Blocks.register("blue_roof_gentle_side", GenericStairBlock::new);
        blueRoofRidgeBlock = XKRegistryHandler.Blocks.register("blue_roof_ridge", RoofRidgeBlock::new);
        blueRoofSideBlock = XKRegistryHandler.Blocks.register("blue_roof_side", GenericStairBlock::new);
        blueRoofSteepBlock = XKRegistryHandler.Blocks.register("blue_roof_steep", GenericStairBlock::new);
        blueRoofSteepSideBlock = XKRegistryHandler.Blocks.register("blue_roof_steep_side", GenericStairBlock::new);
        blueTilesBlock = XKRegistryHandler.Blocks.register("blue_tiles", TilesBlock::new);
        blueTileSlabBlock = XKRegistryHandler.Blocks.register("blue_tile_slab", GenericSlabBlock::new);
        blueTileStairBlock = XKRegistryHandler.Blocks.register("blue_tile_stair", TileStairBlock::new);
    }
}
