package com.teamfractal.xkdeco.common.block.init.eastern;

import com.teamfractal.xkdeco.common.block.base.WoodStairBlock;
import com.teamfractal.xkdeco.common.block.base.WoodWallBlock;
import com.teamfractal.xkdeco.common.block.base.woodensuite.*;
import com.teamfractal.xkdeco.common.util.XKRegistryHandler;
import net.minecraft.world.level.block.Block;
import net.minecraftforge.fmllegacy.RegistryObject;

public class XKWoodSuiteBlocks {
    public static RegistryObject<Block> ebonyBigTableBlock;
    public static RegistryObject<Block> ebonyBracketInterpolationBlock;
    public static RegistryObject<Block> ebonyBracketInterpolationHollowBlock;
    public static RegistryObject<Block> ebonyBracketSetBlock;
    public static RegistryObject<Block> ebonyChairBlock;
    public static RegistryObject<Block> ebonyColumnHeadBlock;
    public static RegistryObject<Block> ebonyColumnHollowWallBlock;
    public static RegistryObject<Block> ebonyColumnMudWallBlock;
    public static RegistryObject<Block> ebonyColumnWoodWallBlock;
    public static RegistryObject<Block> ebonyDeskBlock;
    public static RegistryObject<Block> ebonyDoorBlock;
    public static RegistryObject<Block> ebonyDoubleDoorsBlock;
    public static RegistryObject<Block> ebonyFenceBlock;
    public static RegistryObject<Block> ebonyFenceGateBlock;
    public static RegistryObject<Block> ebonyFenceHeadBlock;
    public static RegistryObject<Block> ebonyFenceObliqueBlock;
    public static RegistryObject<Block> ebonyFenceObliqueSteepBlock;
    public static RegistryObject<Block> ebonyFlipWindowBlock;
    public static RegistryObject<Block> ebonyGooseneckChairBlock;
    public static RegistryObject<Block> ebonyGooseneckChairColumnBlock;
    public static RegistryObject<Block> ebonyImplicateBlock;
    public static RegistryObject<Block> ebonyObliqueBraceBlock;
    public static RegistryObject<Block> ebonyLogBlock;
    public static RegistryObject<Block> ebonyWoodBlock;
    public static RegistryObject<Block> ebonyPlanksBlock;
    public static RegistryObject<Block> ebonyScreenBlock;
    public static RegistryObject<Block> ebonyShelfBlock;
    public static RegistryObject<Block> ebonySlabBlock;
    public static RegistryObject<Block> ebonyStairsBlock;
    public static RegistryObject<Block> ebonyTableBlock;
    public static RegistryObject<Block> ebonyTrapdoorBlock;
    public static RegistryObject<Block> ebonyWallBlock;
    public static RegistryObject<Block> ebonyWindowBlock;

    public static RegistryObject<Block> mahoganyBigTableBlock;
    public static RegistryObject<Block> mahoganyBracketInterpolationBlock;
    public static RegistryObject<Block> mahoganyBracketInterpolationHollowBlock;
    public static RegistryObject<Block> mahoganyBracketSetBlock;
    public static RegistryObject<Block> mahoganyChairBlock;
    public static RegistryObject<Block> mahoganyColumnHeadBlock;
    public static RegistryObject<Block> mahoganyColumnHollowWallBlock;
    public static RegistryObject<Block> mahoganyColumnMudWallBlock;
    public static RegistryObject<Block> mahoganyColumnWoodWallBlock;
    public static RegistryObject<Block> mahoganyDeskBlock;
    public static RegistryObject<Block> mahoganyDoorBlock;
    public static RegistryObject<Block> mahoganyDoubleDoorsBlock;
    public static RegistryObject<Block> mahoganyFenceBlock;
    public static RegistryObject<Block> mahoganyFenceGateBlock;
    public static RegistryObject<Block> mahoganyFenceHeadBlock;
    public static RegistryObject<Block> mahoganyFenceObliqueBlock;
    public static RegistryObject<Block> mahoganyFenceObliqueSteepBlock;
    public static RegistryObject<Block> mahoganyFlipWindowBlock;
    public static RegistryObject<Block> mahoganyGooseneckChairBlock;
    public static RegistryObject<Block> mahoganyGooseneckChairColumnBlock;
    public static RegistryObject<Block> mahoganyImplicateBlock;
    public static RegistryObject<Block> mahoganyObliqueBraceBlock;
    public static RegistryObject<Block> mahoganyLogBlock;
    public static RegistryObject<Block> mahoganyWoodBlock;
    public static RegistryObject<Block> mahoganyPlanksBlock;
    public static RegistryObject<Block> mahoganyScreenBlock;
    public static RegistryObject<Block> mahoganyShelfBlock;
    public static RegistryObject<Block> mahoganySlabBlock;
    public static RegistryObject<Block> mahoganyStairsBlock;
    public static RegistryObject<Block> mahoganyTableBlock;
    public static RegistryObject<Block> mahoganyTrapdoorBlock;
    public static RegistryObject<Block> mahoganyWallBlock;
    public static RegistryObject<Block> mahoganyWindowBlock;

    public static void register(){
        ebonyBigTableBlock = XKRegistryHandler.Blocks.register("ebony_big_table", TableBlock::new);
        ebonyBracketInterpolationBlock = XKRegistryHandler.Blocks.register("ebony_bracket_interpolation", WoodStairBlock::new);
        ebonyBracketInterpolationHollowBlock = XKRegistryHandler.Blocks.register("ebony_bracket_interpolation_hollow", WoodStairBlock::new);
        ebonyBracketSetBlock = XKRegistryHandler.Blocks.register("ebony_bracket_set", WoodStairBlock::new);
        ebonyChairBlock = XKRegistryHandler.Blocks.register("ebony_chair", ChairBlock::new);
        ebonyColumnHeadBlock = XKRegistryHandler.Blocks.register("ebony_column_head", WoodColumnHeadBlock::new);
        ebonyColumnHollowWallBlock = XKRegistryHandler.Blocks.register("ebony_column_hollow_wall", WoodWallBlock::new);
        ebonyColumnMudWallBlock = XKRegistryHandler.Blocks.register("ebony_column_mud_wall", WoodWallBlock::new);
        ebonyColumnWoodWallBlock = XKRegistryHandler.Blocks.register("ebony_column_wood_wall", WoodWallBlock::new);
        ebonyDeskBlock = XKRegistryHandler.Blocks.register("ebony_desk", DeskBlock::new);
        ebonyDoorBlock = XKRegistryHandler.Blocks.register("ebony_door", WoodDoorBlock::new);
        ebonyDoubleDoorsBlock = XKRegistryHandler.Blocks.register("ebony_double_doors", WoodFenceGateBlock::new);
        ebonyFenceBlock = XKRegistryHandler.Blocks.register("ebony_fence", WoodFenceBlock::new);
        ebonyFenceGateBlock = XKRegistryHandler.Blocks.register("ebony_fence_gate", WoodFenceGateBlock::new);
        ebonyFenceHeadBlock = XKRegistryHandler.Blocks.register("ebony_fence_head", FenceHeadBlock::new);
        ebonyFenceObliqueBlock = XKRegistryHandler.Blocks.register("ebony_fence_oblique", FenceObliqueBlock::new);
        ebonyFenceObliqueSteepBlock = XKRegistryHandler.Blocks.register("ebony_fence_oblique_steep", FenceObliqueBlock::new);
        ebonyFlipWindowBlock = XKRegistryHandler.Blocks.register("ebony_flip_window", WoodFenceGateBlock::new);
        ebonyGooseneckChairBlock = XKRegistryHandler.Blocks.register("ebony_gooseneck_chair", WoodStairBlock::new);
        ebonyGooseneckChairColumnBlock = XKRegistryHandler.Blocks.register("ebony_gooseneck_chair_column", WoodStairBlock::new);
        ebonyImplicateBlock = XKRegistryHandler.Blocks.register("ebony_implicate", WoodFenceGateBlock::new);
        ebonyObliqueBraceBlock = XKRegistryHandler.Blocks.register("ebony_oblique_brace", ObliqueBraceBlock::new);
        ebonyLogBlock = XKRegistryHandler.Blocks.register("ebony_log", LogBlock::new);
        ebonyWoodBlock = XKRegistryHandler.Blocks.register("ebony_wood", LogBlock::new);
        ebonyPlanksBlock = XKRegistryHandler.Blocks.register("ebony_planks", PlanksBlock::new);
        ebonyScreenBlock = XKRegistryHandler.Blocks.register("ebony_screen", WoodDoorBlock::new);
        ebonyShelfBlock = XKRegistryHandler.Blocks.register("ebony_shelf", ShelfBlock::new);
        ebonySlabBlock = XKRegistryHandler.Blocks.register("ebony_slab", WoodSlabBlock::new);
        ebonyStairsBlock = XKRegistryHandler.Blocks.register("ebony_stairs", WoodStairBlock::new);
        ebonyTableBlock = XKRegistryHandler.Blocks.register("ebony_table", TableBlock::new);
        ebonyTrapdoorBlock = XKRegistryHandler.Blocks.register("ebony_trapdoor", WoodTrapdoorBlock::new);
        ebonyWallBlock = XKRegistryHandler.Blocks.register("ebony_wall", WoodWallBlock::new);
        ebonyWindowBlock = XKRegistryHandler.Blocks.register("ebony_window", WoodFenceGateBlock::new);

        mahoganyBigTableBlock = XKRegistryHandler.Blocks.register("mahogany_big_table", TableBlock::new);
        mahoganyBracketInterpolationBlock = XKRegistryHandler.Blocks.register("mahogany_bracket_interpolation", WoodStairBlock::new);
        mahoganyBracketInterpolationHollowBlock = XKRegistryHandler.Blocks.register("mahogany_bracket_interpolation_hollow", WoodStairBlock::new);
        mahoganyBracketSetBlock = XKRegistryHandler.Blocks.register("mahogany_bracket_set", WoodStairBlock::new);
        mahoganyChairBlock = XKRegistryHandler.Blocks.register("mahogany_chair", ChairBlock::new);
        mahoganyColumnHeadBlock = XKRegistryHandler.Blocks.register("mahogany_column_head", WoodColumnHeadBlock::new);
        mahoganyColumnHollowWallBlock = XKRegistryHandler.Blocks.register("mahogany_column_hollow_wall", WoodWallBlock::new);
        mahoganyColumnMudWallBlock = XKRegistryHandler.Blocks.register("mahogany_column_mud_wall", WoodWallBlock::new);
        mahoganyColumnWoodWallBlock = XKRegistryHandler.Blocks.register("mahogany_column_wood_wall", WoodWallBlock::new);
        mahoganyDeskBlock = XKRegistryHandler.Blocks.register("mahogany_desk", DeskBlock::new);
        mahoganyDoorBlock = XKRegistryHandler.Blocks.register("mahogany_door", WoodDoorBlock::new);
        mahoganyDoubleDoorsBlock = XKRegistryHandler.Blocks.register("mahogany_double_doors", WoodFenceGateBlock::new);
        mahoganyFenceBlock = XKRegistryHandler.Blocks.register("mahogany_fence", WoodFenceBlock::new);
        mahoganyFenceGateBlock = XKRegistryHandler.Blocks.register("mahogany_fence_gate", WoodFenceGateBlock::new);
        mahoganyFenceHeadBlock = XKRegistryHandler.Blocks.register("mahogany_fence_head", FenceHeadBlock::new);
        mahoganyFenceObliqueBlock = XKRegistryHandler.Blocks.register("mahogany_fence_oblique", FenceObliqueBlock::new);
        mahoganyFenceObliqueSteepBlock = XKRegistryHandler.Blocks.register("mahogany_fence_oblique_steep", FenceObliqueBlock::new);
        mahoganyFlipWindowBlock = XKRegistryHandler.Blocks.register("mahogany_flip_window", WoodFenceGateBlock::new);
        mahoganyGooseneckChairBlock = XKRegistryHandler.Blocks.register("mahogany_gooseneck_chair", WoodStairBlock::new);
        mahoganyGooseneckChairColumnBlock = XKRegistryHandler.Blocks.register("mahogany_gooseneck_chair_column", WoodStairBlock::new);
        mahoganyImplicateBlock = XKRegistryHandler.Blocks.register("mahogany_implicate", WoodFenceGateBlock::new);
        mahoganyObliqueBraceBlock = XKRegistryHandler.Blocks.register("mahogany_oblique_brace", ObliqueBraceBlock::new);
        mahoganyLogBlock = XKRegistryHandler.Blocks.register("mahogany_log", LogBlock::new);
        mahoganyWoodBlock = XKRegistryHandler.Blocks.register("mahogany_wood", LogBlock::new);
        mahoganyPlanksBlock = XKRegistryHandler.Blocks.register("mahogany_planks", PlanksBlock::new);
        mahoganyScreenBlock = XKRegistryHandler.Blocks.register("mahogany_screen", WoodDoorBlock::new);
        mahoganyShelfBlock = XKRegistryHandler.Blocks.register("mahogany_shelf", ShelfBlock::new);
        mahoganySlabBlock = XKRegistryHandler.Blocks.register("mahogany_slab", WoodSlabBlock::new);
        mahoganyStairsBlock = XKRegistryHandler.Blocks.register("mahogany_stairs", WoodStairBlock::new);
        mahoganyTableBlock = XKRegistryHandler.Blocks.register("mahogany_table", TableBlock::new);
        mahoganyTrapdoorBlock = XKRegistryHandler.Blocks.register("mahogany_trapdoor", WoodTrapdoorBlock::new);
        mahoganyWallBlock = XKRegistryHandler.Blocks.register("mahogany_wall", WoodWallBlock::new);
        mahoganyWindowBlock = XKRegistryHandler.Blocks.register("mahogany_window", WoodFenceGateBlock::new);
    }

}
